### PR TITLE
Remove redundant call: remove_epsilon

### PR DESCRIPTION
**Pull request by vhavlena**
Remove redundant call of remove_epsilon.

### CODE REVIEW

**Comment by Adda0** [comment]
Are we sure that we cannot get epsilon automata from Mata? What operations are we calling here?

**Comment by vhavlena** [comment]
We must be sure that automata from regexes are epsilon-free. Then we use just reduce, minimize, concatenate, product, maybe union. The basic operations that should not introduce epsilons.

**Comment by Adda0** [comment]
I verified that we create NFAs from regexes without epsilon symbols. Hence, the PR should be OK as of now.

**Review by Adda0 — APPROVED** [review]

**Review by Adda0 — APPROVED** [review]
Looks good to me. Let us see how it will affect the results.

**Pull request merged**
