### PR TITLE
Language equivalence

### PR DESCRIPTION
**Pull request by vhavlena**
This PR introduces a decision procedure for language equivalence

### CODE REVIEW

**Comment by vhavlena** [comment]
@jurajsic Could you please run the regular blah benchmark?

**Review by jurajsic — APPROVED** [review]
Looks ok, there are no errors in the regex benchmark.

**Comment by vhavlena** [comment]
If you don't have some other comments, I will merge it

**Comment by Adda0** [comment]
Give me just a moment to finish reviewing the code. No problems so far.

**Review by Adda0 — APPROVED** [review]
The changes seem fine to me, too.

**Comment by jurajsic** [comment]
You can merge it

**Pull request merged**
