### PR TITLE
Variables fix

### PR DESCRIPTION
**Pull request by vhavlena**
This PR changes `get_variables` to `get_str_variables` with string sort checking. As far as I know, we do not need getting variables with different sort than strings.

### CODE REVIEW

**Review by Adda0 — APPROVED** [review]
Seems good to me. As of now, we do not know of any better solution to our problem.

**Comment by vhavlena** [comment]
I also updated `get_init_length_vars` in order to take only variables occurring within the current automata assignment

**Review by Adda0 — APPROVED** [review]
I believe the last change is also reasonable.

**Comment by vhavlena** [comment]
I will merge it then

**Pull request merged**
